server:
  port: 8008

spring:
  data:
    mongodb:
      uri: "mongodb://192.168.200.100:17017/neurotales_db"

knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
  cors: true

langchain4j:
  open-ai:
    chat-model:
      base-url: "http://langchain4j.dev/demo/openai/v1"
      api-key: demo
      model-name: gpt-4o-mini
  #      log-requests: true
  #      log-responses: true
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true
      temperature: 0.8
      timeout: PT60S
logging:
  level:
    root: info
