server:
  port: 8008

spring:
#  data:
#    mongodb:
#      uri: "mongodb://192.168.200.100:17017/neurotales_db"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  threads:
    virtual:
      enabled: true
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s



knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
  cors: true

langchain4j:
  open-ai:
    chat-model:
      base-url: "http://langchain4j.dev/demo/openai/v1"
      api-key: demo
      model-name: gpt-4o-mini
  #      log-requests: true
  #      log-responses: true
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true
      temperature: 0.8
      timeout: PT60S

  community:
    dashscope:
      chat-model:
        api-key: "sk-272227be632f47c2bc95bc0d0ac14188"
        model-name: qwen-max





logging:
  level:
    root: debug

